services:
  app:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --reload --host 0.0.0.0 --port 8000
  postgres-service:
    container_name: postgres-container
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgres/data
    env_file:
      - ./.env

volumes:
  postgres-data:
    external: false
